# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

# from PyQt5 import QtCore, QtGui, QtWidgets
# from PyQt5.QtWidgets import QApplication, QMainWindow
#
# from conn_com import Communication, Ret, Engine1
#
#
# class Ui_MainWindow(QMainWindow):
#     def __init__(self):
#         super(Ui_MainWindow, self).__init__()
#         self.setupUi(self)
#
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(1038, 736)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         self.pushButton = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton.setGeometry(QtCore.QRect(60, 50, 75, 23))
#         self.pushButton.setObjectName("pushButton")
#         self.pushButton.clicked.connect(self.on_Click1)
#         self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton_4.setGeometry(QtCore.QRect(140, 100, 75, 23))
#         self.pushButton_4.setObjectName("pushButton_4")
#         self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton_2.setGeometry(QtCore.QRect(140, 50, 75, 23))
#         self.pushButton_2.setObjectName("pushButton_2")
#         self.pushButton_2.clicked.connect(self.on_Click2)
#         self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton_3.setGeometry(QtCore.QRect(60, 100, 75, 23))
#         self.pushButton_3.setObjectName("pushButton_3")
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 23))
#         self.menubar.setObjectName("menubar")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)
#
#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         self.pushButton.setText(_translate("MainWindow", "开灯"))
#         self.pushButton_4.setText(_translate("MainWindow", "关门"))
#         self.pushButton_2.setText(_translate("MainWindow", "关灯"))
#         self.pushButton_3.setText(_translate("MainWindow", "开门"))
#
#     def on_Click1(self):
#         #  openLed
#         self.sender()
#         print("sss")
#         data = bytearray.fromhex("a55a050103028067b1")
#         Engine1.Send_data(data)
#         #   self.pushButton_3.setVisible(False)
#
#
#
#     def on_Click2(self):
#         # 关灯
#         self.sender()
#         print("2222")
#         data = bytearray.fromhex("a55a0501030200ef20")
#         Engine1.Send_data(data)
